In [1]:
def calculator(list_of_numbers):
    result = 0
    for number in list_of_numbers:
        if type(number) == int:
            result = result + number
        else:
            print('ERROR: Wait, a calculator needs numbers, what are you doing?')
    print(f'The result is {result}') 

In [39]:
import numpy as np
import random as r

In [3]:
lst = [1, 2, 3, 4, 5]

In [4]:
np.array(lst)

array([1, 2, 3, 4, 5])

In [5]:
first_arr = np.array(lst)

In [6]:
first_arr[0]

1

In [11]:
first_arr[5] = 7

IndexError: index 5 is out of bounds for axis 0 with size 5

In [12]:
first_arr[2] = 7

In [9]:
first_arr

array([1, 2, 7, 4, 5])

In [10]:
first_arr.sum()

19

In [13]:
first_arr.mean()

3.8

In [23]:
def calculator(array_of_numbers, operation):
    print(f'The result is {operation(array_of_numbers)}') 

In [24]:
calculator(first_arr, sum)

The result is 19


In [26]:
calculator(first_arr, np.sum)

The result is 19


In [28]:
calculator(first_arr, np.mean)

The result is 3.8


In [29]:
matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [34]:
matrix = np.array(matrix)

In [31]:
calculator(np.array(matrix), np.sum)

The result is 45


In [32]:
calculator(np.array(matrix), np.mean)

The result is 5.0


In [37]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [35]:
matrix.mean(axis=0)

array([4., 5., 6.])

In [38]:
matrix.mean(axis=1)

array([2., 5., 8.])

In [42]:
random_matrix = np.random((3, 3))

TypeError: 'module' object is not callable

In [43]:
random_matrix = np.random.random((3, 3))

In [44]:
random_matrix

array([[0.81377032, 0.16816247, 0.3323042 ],
       [0.74385997, 0.28944207, 0.35388741],
       [0.6038964 , 0.81561563, 0.41730852]])

In [ ]:
random_matrix2 

In [50]:
random_matrix = np.random.random((1, 3))

In [51]:
random_matrix

array([[0.58966522, 0.91094866, 0.01411257]])

In [52]:
random_matrix = np.random.random((3, 1))

In [53]:
random_matrix

array([[0.56619631],
       [0.20954328],
       [0.55399071]])

In [54]:
random_matrix = np.random.random((4, 4, 4))

In [55]:
random_matrix

array([[[0.86547936, 0.887993  , 0.49937858, 0.34336905],
        [0.68717143, 0.24855697, 0.85872225, 0.56817655],
        [0.11746017, 0.69894645, 0.98955927, 0.94762353],
        [0.23827658, 0.77658569, 0.24574137, 0.51684977]],

       [[0.48139041, 0.14679323, 0.83474536, 0.17149598],
        [0.84448857, 0.08399291, 0.54417035, 0.57282553],
        [0.58873   , 0.02512655, 0.01352575, 0.16754961],
        [0.2630931 , 0.56098726, 0.42267649, 0.68498623]],

       [[0.87006318, 0.49628609, 0.80959161, 0.26138557],
        [0.67607296, 0.92207292, 0.63096625, 0.57309605],
        [0.30173826, 0.33831248, 0.1072039 , 0.23608399],
        [0.98015465, 0.67206925, 0.86089402, 0.25581431]],

       [[0.42160444, 0.2720789 , 0.72747511, 0.60331325],
        [0.91872562, 0.93134392, 0.20025561, 0.13039141],
        [0.86249846, 0.10135454, 0.46435606, 0.54024779],
        [0.45573383, 0.4323866 , 0.00917771, 0.77582864]]])

In [56]:
random_matrix.sum()

32.73504472691317

In [57]:
random_matrix2 = np.random.random((3, 3))

In [59]:
random_matrix2

array([[0.37456443, 0.16439103, 0.02220281],
       [0.87762428, 0.84852146, 0.17813235],
       [0.1696385 , 0.2979917 , 0.02348957]])

In [58]:
np.add(random_matrix, random_matrix2)

ValueError: operands could not be broadcast together with shapes (4,4,4) (3,3) 

In [60]:
random_matrix.reshape(random_matrix2.shape)

ValueError: cannot reshape array of size 64 into shape (3,3)

In [62]:
random_matrix2.reshape(random_matrix.shape)

ValueError: cannot reshape array of size 9 into shape (4,4,4)

In [61]:
random_matrix2.shape

(3, 3)

In [64]:
random_matrix2[1, :]

array([0.87762428, 0.84852146, 0.17813235])

In [65]:
new_ranmat = np.random.random((3, 3))

In [66]:
new_ranmat2 = np.random.random((3, 3))

In [67]:
np.add(new_ranmat, new_ranmat2)

array([[1.85994963, 1.63980471, 1.01766734],
       [1.12533753, 0.96012874, 0.98492249],
       [0.86376483, 0.56749075, 1.17794579]])

In [68]:
np.subtract(new_ranmat, new_ranmat2)

array([[ 0.11936874, -0.21261391, -0.26211125],
       [-0.45613242, -0.63252106, -0.01608884],
       [-0.85463054,  0.14872657,  0.6679217 ]])

In [69]:
np.multiply(new_ranmat, new_ranmat2)

array([[0.86129093, 0.6609387 , 0.24173613],
       [0.26458195, 0.13044108, 0.24245336],
       [0.00392408, 0.07498154, 0.23535922]])

In [70]:
np.divide(new_ranmat, new_ranmat2)

array([[1.13715965, 0.77044724, 0.59038032],
       [0.42315386, 0.20569976, 0.96785483],
       [0.00531559, 1.71031179, 3.6191771 ]])

In [76]:
last_matrix = np.array([[1, 2, 3], [7, 10, 0], [1, 3, -2]])

In [78]:
np.divide(new_ranmat, last_matrix)

/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[ 0.98965918,  0.3567977 ,  0.12592602],
       [ 0.04780037,  0.01638038,         inf],
       [ 0.00456714,  0.11936955, -0.46146687]])

In [74]:
new_ranmat.shape

(3, 3)

In [77]:
last_matrix.shape

(3, 3)

In [79]:
np.inf

inf

In [80]:
np.inf / np.inf

nan

In [81]:
np.inf / np.nan

nan

In [ ]:
NaN = "Not a Number"